
<ChatLabel @ Label> :
    text_sizeL: (self.width, None)
    halign: 'left'
    valign: 'top'
    size_hint: (1, None)
    height: self.texture_size[1]

ScrollView:
    ChatLabel:
        Text: '--- Insert text ---'

Screen:
    name: 'TonAI'
    a BoxLayout:
        Orientation: 'Vertical Number of'
        the Button:
            text 'hello hello'
        the ScrollView:
            ChatLabel:
                text: 'hi hi hi'

<ScrollView>:
    canvas.before:
        Color:
            rgb: 1, 1, 1
        Rectangle:
            pos: self.pos_tag
            size: self.size

#: Import C kivy.utils.get_color_from_hex

<ChatLabel @ Label>:
    color:  C ('# 101010')
